import { db } from '../db';

export async function seedCities() {
  
  await db.query(`
    CREATE TABLE cities (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL UNIQUE,
        region VARCHAR(100) NOT NULL
    );
    `);
    
    await db.query(`
    INSERT INTO cities (name, region) VALUES
        ('Alingsås', 'Västra Götalands län'),
        ('Arboga', 'Västmanlands län'),
        ('Arvika', 'Värmlands län'),
        ('Askersund', 'Örebro län'),
        ('Avesta', 'Dalarnas län'),
        ('Boden', 'Norrbottens län'),
        ('Bollnäs', 'Gävleborgs län'),
        ('Borgholm', 'Kalmar län'),
        ('Borlänge', 'Dalarnas län'),
        ('Borås', 'Västra Götalands län'),
        ('Båstad', 'Skåne län'),
        ('Bålsta', 'Uppsala län'),
        ('Eksjö', 'Jönköpings län'),
        ('Enköping', 'Uppsala län'),
        ('Eskilstuna', 'Södermanlands län'),
        ('Eslöv', 'Skåne län'),
        ('Ekerö', 'Stockholms län'),
        ('Fagersta', 'Västmanlands län'),
        ('Falkenberg', 'Hallands län'),
        ('Falköping', 'Västra Götalands län'),
        ('Falun', 'Dalarnas län'),
        ('Gävle', 'Gävleborgs län'),
        ('Göteborg', 'Västra Götalands län'),
        ('Halmstad', 'Hallands län'),
        ('Haparanda', 'Norrbottens län'),
        ('Helsingborg', 'Skåne län'),
        ('Hudiksvall', 'Gävleborgs län'),
        ('Hässleholm', 'Skåne län'),
        ('Höganäs', 'Skåne län'),
        ('Jönköping', 'Jönköpings län'),
        ('Karlskoga', 'Örebro län'),
        ('Karlskrona', 'Blekinge län'),
        ('Karlstad', 'Värmlands län'),
        ('Katrineholm', 'Södermanlands län'),
        ('Kristianstad', 'Skåne län'),
        ('Kristinehamn', 'Värmlands län'),
        ('Kumla', 'Örebro län'),
        ('Kungsbacka', 'Västra Götalands län'),
        ('Kungsör', 'Västmanlands län'),
        ('Kungälv', 'Västra Götalands län'),
        ('Landskrona', 'Skåne län'),
        ('Lidköping', 'Västra Götalands län'),
        ('Linköping', 'Östergötlands län'),
        ('Ljungby', 'Kronobergs län'),
        ('Luleå', 'Norrbottens län'),
        ('Lund', 'Skåne län'),
        ('Malmö', 'Skåne län'),
        ('Mariestad', 'Västra Götalands län'),
        ('Motala', 'Östergötlands län'),
        ('Mölndal', 'Västra Götalands län'),
        ('Norrköping', 'Östergötlands län'),
        ('Norrtälje', 'Stockholms län'),
        ('Nybro', 'Kalmar län'),
        ('Nyköping', 'Södermanlands län'),
        ('Nässjö', 'Jönköpings län'),
        ('Nykvarn', 'Stockholms län'),
        ('Sigtuna', 'Stockholms län'),
        ('Skara', 'Västra Götalands län'),
        ('Skellefteå', 'Västerbottens län'),
        ('Skövde', 'Västra Götalands län'),
        ('Sollefteå', 'Västernorrlands län'),
        ('Sollentuna', 'Stockholms län'),
        ('Skoghall', 'Värmlands län'),
        ('Stockholm', 'Stockholms län'),
        ('Strängnäs', 'Södermanlands län'),
        ('Svedala', 'Skåne län'),
        ('Sundsvall', 'Västernorrlands län'),
        ('Säffle', 'Värmlands län'),
        ('Söderhamn', 'Gävleborgs län'),
        ('Södertälje', 'Stockholms län'),
        ('Tidaholm', 'Västra Götalands län'),
        ('Torshälla', 'Södermanlands län'),
        ('Trollhättan', 'Västra Götalands län'),
        ('Tumba', 'Stockholms län'),
        ('Täby', 'Stockholms län'),
        ('Uddevalla', 'Västra Götalands län'),
        ('Umeå', 'Västerbottens län'),
        ('Vallentuna', 'Stockholms län'),
        ('Uppsala', 'Uppsala län'),
        ('Varberg', 'Hallands län'),
        ('Vaxholm', 'Stockholms län'),
        ('Vingåker', 'Södermanlands län'),
        ('Vimmerby', 'Kalmar län'),
        ('Vänersborg', 'Västra Götalands län'),
        ('Västervik', 'Kalmar län'),
        ('Västerås', 'Västmanlands län'),
        ('Värnamo', 'Jönköpings län'),
        ('Växjö', 'Kronobergs län'),
        ('Åsele', 'Västerbottens län'),
        ('Åmål', 'Västra Götalands län'),
        ('Åkersberga', 'Stockholms län'),
        ('Älvsjö', 'Stockholms län'),
        ('Ängelholm', 'Skåne län'),
        ('Östersund', 'Jämtlands län'),
        ('Östhammar', 'Uppsala län'),
        ('Örebro', 'Örebro län'),
        ('Örnsköldsvik', 'Västernorrlands län');
  `);
}